#pragma once

// Global includes to be acessible from everywhere.
// Note, that this list shouldn't ever include libraries
// Not acessible everywhere


// Includes generated by external scripts
#include "pregen.h"

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
