#pragma once

// Global includes to be acessible from everywhere.
// Note, that this list shouldn't ever include libraries
// Not acessible everywhere

// Includes generated by external scripts
#include "pregen.h"

// Init order
#include "initprio.h"

// Limitations for C-strings across all EOS
#include "strlimits.h"

// Default libraries
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
