#pragma once

// This file represents macroses/options to be ever generated by external
// scripts

// This file is generated per target chip + board.
// Target: ESP32-S3(LILKAV2)

#include <soc/soc_caps.h>

#define EOS_TARGET_LILKAV2

#define EOS_MAX_DEVICES 32

#define EOS_MAX_CAPS 256

// Enabled drivers:
#define EOS_DRIVER_STORAGE_SD_ENABLED
#define EOS_DRIVER_BUS_SPI_ENABLED
#define EOS_DRIVER_BUS_GPIO_ENABLED
#define EOS_DRIVER_DISPLAY_ST7789_ENABLED

// CPU Core count
#define EOS_CPU_COUNT SOC_CPU_CORES_NUM
// Pin configuration:

// ESP32-S3 has GPIO0..GPIO48 in numbering,
// but GPIO22-GPIO25 do not exist on the chip.
// Using 49 as count so pin number == array index directly.
#define EOS_GPIO_COUNT SOC_GPIO_PIN_COUNT

// Reserved pins — claiming these will be rejected by eos_pin_claim().
// Covers:
//   0, 3, 45, 46  — strapping pins (boot mode, JTAG, VDD_SPI)
//   19, 20        — USB D-/D+ (used by ESP-IDF USB stack)
//   26..32        — SPI0/1 flash + PSRAM (always reserved)
//   33..37        — Octal PSRAM (reserved if using R8 or higher variant)
//   43, 44        — UART0 TX/RX (used by ROM/bootloader console)
//   22, 23, 24, 25 — do not exist on ESP32-S3 silicon
#define EOS_GPIO_RESERVED                                                      \
  {0,  3,  19, 20, 22, 23, 24, 25, 26, 27, 28, 29,                             \
   30, 31, 32, 33, 34, 35, 36, 37, 43, 44, 45}

// I2C
#define EOS_I2C_COUNT SOC_I2C_NUM

// If nothing reserved, just not define it to skip checks
// #define EOS_I2C_RESERVED                                                  {}

// SPI:
// First SPI interface is reserved for an external memory usage
#define EOS_SPI_COUNT SOC_SPI_PERIPH_NUM
#define EOS_SPI_RESERVED {0}

// UART:
#define EOS_UART_COUNT SOC_UART_NUM
#define EOS_UART_RESERVED {0}